general_setup:
    attributes:
        file_path: 'selftest'
        requirements_path: ''
    commands:
        - 'echo Testing'
python:
    file_setup:
    # src/config_parser.py:
    #     tests:
    src/file_builder.py:
        tests:
            Script.hash_string:
                - _ -> 46b9dd2b
                - hello -> 1234075a
                - tests/code/test.py -> '81174737'
            getImports:
                csv_path: 'selftest/data/code_builder_data.csv'
            getFunctionHead:
                csv_path: 'selftest/data/code_builder_data.csv'
            getFunctionBody:
                csv_path: 'selftest/data/code_builder_data.csv'
            getFunctionCustom:
                csv_path: 'selftest/data/code_builder_data.csv'
            _isCodeFileValid:
                csv_path: 'selftest/data/code_builder_data.csv'
    # src/hook.py:
    #     tests:
    # src/layer.py:
    #     tests:
    # src/log_level.py:
    #     tests:
    # src/prototype.py:
    #     tests:
    file_shutdown:
general_shutdown:
